FROM python:3.9

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

ADD src/service_monitor/api /code/service_monitor/api
ADD src/service_monitor/shared /code/service_monitor/shared

CMD ["uvicorn", "service_monitor.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
