api_repo = "<api repo>"
compute_repo = "<compute repo>"
database_name = "url_db"
database_user = "terraform"
execution_rate = "rate(10 minutes)"
cidr = "10.32.0.0/16"
min_pool = 5
max_pool = 100
timeout = 2